Implement eight digit code for UI
tripleblindmarket/private-kit pull request #1165
Opened 2020-07-02 16:15 UTC by zhaccc

#### Description:

Implement support for 8 digit code instead of 6 digit code.

The design should take a look at this because since we use 8 text inputs it now looks kinda squashed (check the screens below).

#### Screenshots:

_iPhone SE (1st Generation):_
![image]()
<img src="https://user-images.githubusercontent.com/24491937/86385007-dd750380-bc8f-11ea-8b5c-5871ae95c0aa.png" width="500">

_iPhone 11 Pro Max:_
![image](https://user-images.githubusercontent.com/24491937/86384459-0e086d80-bc8f-11ea-967b-4e52e4efb746.png)

2020-07-02 16:30 UTC, JacobJaffe requested changes

2020-07-02 16:30 UTC, JacobJaffe commented on app/views/Export/ExportCodeInput.js
> +const CODE_LENGTH = 8;
This should only be for BT I believe

2020-07-06 12:08 UTC, zhaccc commented on app/views/Export/ExportCodeInput.js
> +const CODE_LENGTH = 8;
Yep, as we discussed.

2020-07-06 16:04 UTC, johnschoeman approved these changes
LGTM, would appreciate your review on this one: https://github.com/Path-Check/covid-safe-paths/pull/1174 ! as it moves away from sharing this screen at this point.

2020-07-07 14:30 UTC, closed without merging