Add badge indicator when user has new exposure
tripleblindmarket/private-kit pull request #1286
Opened 2020-07-17 20:18 UTC by amandabeiner

### Testing Notes ###
- Simulate an exposure
- Expect a yellow badge to appear above the calendar icon in the main
tab navigator
- Visit the calendar tab
- Expect the badge to disappear
Include instructions for reviewers to run tests related to this PR.

 ### Fixed Issues ###
Resolves [issue](https://trello.com/c/cfe33Gbb/194-as-a-user-i-want-to-see-a-badge-on-the-calendar-icon-when-i-have-an-en-so-that-i-notice-it-as-soon-as-possible) where user was not receiving a badge on the calendar icon when they had
a new exposure.

 ### Tech Notes ###
When the exposureInfoSubscription is called after the user has a new
exposure, we were not updating the ExposureHistory context with the
information that a new exposure was found. This commit:
- Updates the userHasNewExposure when the subscription is called
- Removes a resetExposures function that is unused

#### Screenshots:

![dot](https://user-images.githubusercontent.com/21161427/87827414-e09ff000-c848-11ea-839f-6527c6d0b636.gif)

Co-Authored-By: Thomas G Paresi <tparesi@gmail.com>

2020-07-17 20:22 UTC, aledustet approved these changes
🚢  :shipit:

2020-07-17 20:43 UTC, mattThousand requested changes
If exposures are considered "viewed" only if the user has visited the calendar screen, we should persist the indicator between app launches (if a user force quits the app before "viewing" their new exposures, and then relaunches, the indicator should still be present) 🤔

2020-07-17 20:47 UTC, aledustet commented
Shouldn't this behave like the notifications badge? Once a user opens an app the badge is gone, right?

2020-07-17 20:52 UTC, mattThousand commented
ah, this might be a platform-specific convention (I am not familiar with android). On iOS, badges (https://developer.apple.com/documentation/usernotifications/unnotificationcontent/1649864-badge) on the app icon and internal to the app usually require a specific action to be taken, such as in Messages you need to visit a specific unread message thread to hide the badge. In our case I believe visiting the calendar is the UX that constitutes updating "read/unread" state

2020-07-20 23:15 UTC, johnschoeman commented
this looks like its no longer necessary in the GPS repo, should the pr be closed @amandabeiner ?

2020-07-21 16:18 UTC, closed without merging