minor ux and accessibility updates
tripleblindmarket/private-kit pull request #862
Opened 2020-05-19 14:43 UTC by jeffstolz

#### Description:

This commit updates the text throughout the app to follow the WCAG AA color accessibility guidelines.

#### Linked issues:

No applicable issue to link to.

#### Screenshots:

<img width="376" alt="about" src="https://user-images.githubusercontent.com/2924479/82340696-85bf5900-99bd-11ea-99bf-04c036b9a22b.png">
<img width="376" alt="choose_health_authority" src="https://user-images.githubusercontent.com/2924479/82340698-8657ef80-99bd-11ea-81a3-c487d8758379.png">
<img width="377" alt="dashboard" src="https://user-images.githubusercontent.com/2924479/82340700-86f08600-99bd-11ea-94a3-76b2f9a2311c.png">
<img width="586" alt="enable_notification" src="https://user-images.githubusercontent.com/2924479/82340703-86f08600-99bd-11ea-8e46-337aea06d086.png">
<img width="376" alt="exposure_history" src="https://user-images.githubusercontent.com/2924479/82340704-87891c80-99bd-11ea-8b67-6a0513120102.png">
<img width="784" alt="exposure_notification" src="https://user-images.githubusercontent.com/2924479/82340708-87891c80-99bd-11ea-8002-7b1a664a1819.png">
<img width="377" alt="onboarding" src="https://user-images.githubusercontent.com/2924479/82340711-8821b300-99bd-11ea-94e3-2964c1eb411d.png">

#### How to test:

Running an iOS simulator:

1. Open a new instance of the app.
2. Ensure first onboarding screen matches attach screenshot "onboarding".
3. Complete onboarding.
4. Open the app dashboard, ensure the screen matches attached screenshot "dashboard".
5. Select "Choose Health Authority", ensure the screen matches attached screenshot "choose_health_authority".
6. Return to dashboard, select "Exposure History", ensure the screen matches attached screenshot "exposure_history."
7. Return to dashboard, select "About", ensure the screen matches attached screenshot "about".

2020-05-19 14:47 UTC, johnschoeman reviewed
code LGTM!  looks like some extra stuff came along for the ride though, which should be removed.

2020-05-19 14:47 UTC, johnschoeman commented on gps/app/views/onboarding/Onboarding1.js
>      // alpha needs to be in the bg color otherwise it fades the contained text
i think this comment can be removed.

2020-05-19 18:12 UTC, tstirrat commented
Hey, thanks for looking at this, black is a big departure from our current design system, and I was fairly sure we were already AA compliant or not far off (definitely not AAA yet though).

Check in with folks in the uiux channel (especially @driedgrape) on color before working more on this. Jared has already been working a lot on typography and contrast, but his changes are likely not be reflected in the app yet.

2020-05-19 18:13 UTC, tstirrat requested changes
See comment about uiux discussion

2020-05-19 20:34 UTC, jeffstolz commented
> Hey, thanks for looking at this, black is a big departure from our current design system, and I was fairly sure we were already AA compliant or not far off (definitely not AAA yet though).
> 
> Check in with folks in the uiux channel (especially @driedgrape) on color before working more on this. Jared has already been working a lot on typography and contrast, but his changes are likely not be reflected in the app yet.

@tstirrat Thanks for the feedback. Not sure if you synced with Ali on this - we discussed with Sam on getting these changes in and updating the design system after. The violet headings were AA, but the back button on the NavigationBarWrapper and the secondary body copy were failing the tests. We chose to switch to black for the headings so they stood out from the body copy and helped with scanning. You cool if I merge this in, and then I'll meet with Jared to discuss changes to the design system after?

2020-05-21 01:52 UTC, tstirrat commented
I'll let Ali weigh in here (I've pinged her to take a look). I think this puts the app into a non-releasable state until we update the design system and reflect those changes back in here.

2020-05-26 14:18 UTC, closed without merging