Update to Readme
tripleblindmarket/private-kit pull request #929
Opened 2020-05-29 02:13 UTC by aberrey

This is an update to the readme with more information about GAEN and a more expansive explanation of the Safe Paths project. Please review for typos!!!

#### Description:

#### Linked issues:

#### Screenshots:

#### How to test:

2020-05-30 11:46 UTC, alpita-masurkar commented on README.md
> +The rules for GAEN require that each public health authority release their own application. The goal with Project Aurora is to suppor this deployment strategy.
typo-- support*

2020-05-30 11:47 UTC, alpita-masurkar commented on README.md
> +One of the important aspects of the Safe Paths open source project is that it's supported by a large community of volutneers in addition to the open source developer community. More than 1,400 Path C
typo-- volunteers*

2020-05-30 11:48 UTC, alpita-masurkar commented on README.md
> +What’s truly special about Safe Paths is our strong commitment to preserving the privacy of individual users. We're building an application that can help contain outbreaks of COVID-19 without forcing
typo-- sacrifice*

2020-05-30 11:49 UTC, alpita-masurkar requested changes
a few typos... left some comments

2020-05-31 01:11 UTC, tstirrat requested changes

2020-05-31 01:11 UTC, tstirrat commented on README.md
> +What’s truly special about Safe Paths is our strong commitment to preserving the privacy of individual users. We're building an application that can help contain outbreaks of COVID-19 without forcing
The logged data only leave[s] the device if the user chooses to send the information to an authorized public health authority (PHA) as part of the contact tracing [process].

2020-05-31 03:09 UTC, Ferrumofomega reviewed
Added a few comments, mostly spelling but a few other comments included too.

2020-05-31 03:09 UTC, Ferrumofomega commented on README.md
> +Safe Paths is designed to support a range of DCT and public health use cases. Currently the main build uses GPS for location tracking. Our roadmap includes adding support for other location and proxi
Safe Paths is designed to support a range of DCT and public health use cases. Currently the main build uses GPS for location tracking with GAEN BT tracing strategies in active development. Our roadmap includes adding support for other location and proximity technologies, symptom tracking, and communication with PHAs.

2020-05-31 03:09 UTC, Ferrumofomega commented on README.md
> +Safe Paths is designed to support a variety of implementation strategies.
The Safe Paths app is being developed to support a variety of build 'flavors' of the application around core health and tracing functionality. Reach out to our team to discuss creating a `flavor` for your use-case.

2020-05-31 03:09 UTC, Ferrumofomega commented on README.md
> +We welcome public health authorities and other organizations implementing digital contact tracing strategies to create custom builds for their specific needs, incorporate Safe Paths features into the
We welcome public health authorities and other organizations implementing digital contact tracing strategies to create custom builds for their specific needs, incorporate Safe Paths features into their applications, or create downstream projects that stay linked to the Safe Paths project. If intending to fork the repository and develop off of it, be aware that this comes "at your own risk" for continued maintenance.

2020-05-31 03:09 UTC, Ferrumofomega commented on README.md
> +Safe Paths is designed to work with Safe Places, a tool for contact tracing teams to work with location data in the course of contact tracing interviews and to publish points of concern. Without havi
Safe Paths is designed to work with [Safe Places](https://github.com/Path-Check/safeplaces-frontend), a tool for contact tracing teams to work with location data in the course of contact tracing interviews and to publish points of concern. Without having to sharing their own location history, a Safe Paths user can download the points of concern from their PHA to identify if they have had risk of an exposure.

2020-05-31 03:09 UTC, Ferrumofomega commented on README.md
> +One of the important aspects of the Safe Paths open source project is that it's supported by a large community of volutneers in addition to the open source developer community. More than 1,400 Path C
One of the important aspects of the Safe Paths open source project is that it's supported by a large community of volunteers in addition to the open source developer community. Spanning as diverse domains as product management, user research, cryptography, security, compliance, design, and videography more than 1,400 Path Check volunteers are working together to support Safe Paths and help drive adoption around the world.

2020-06-01 04:49 UTC, tstirrat approved these changes

2020-06-01 13:32 UTC, merged