Convert helpers/general and storage.js to ts
tripleblindmarket/private-kit pull request #988
Opened 2020-06-10 20:00 UTC by johnschoeman

Why:
We would like to use typescript on some files which import theses
functions and constants.

This commit:
Updates the files to ts.  Some rather permissive types are being
returned from the functions, which could likely be tightened up in a
future commit.

2020-06-10 20:01 UTC, johnschoeman commented
trying to ship smaller commits

2020-06-10 20:18 UTC, JacobJaffe commented on app/helpers/General.ts
> +      return JSON.parse(data);
Doesn't this return an any type? 
Without explicit setters / getters per payload to the store I think this whole `GetStoreData` needs to be typed as an `any` return

2020-06-10 20:30 UTC, johnschoeman commented on app/helpers/General.ts
> +      return JSON.parse(data);
you are correct! good catch

2020-06-10 21:07 UTC, JacobJaffe requested changes

2020-06-10 21:07 UTC, JacobJaffe commented on app/TracingStrategyAssets.ts
> +import { useTranslation } from 'react-i18next';
It looks like to me this file got added without removing the corresponding .js version?

2020-06-11 14:25 UTC, JacobJaffe approved these changes

2020-06-11 14:30 UTC, tparesi approved these changes
LGTM

2020-06-11 15:12 UTC, merged